robot:
    udp_inbound_command_port: 5800
    udp_outbound_host: "10.45.13.2"
    udp_outbound_port: 8888
    udp_outbound_video_host: "10.45.13.5"
    udp_outbound_video_port: 5802
    turret_camera_height: 28.5
    turret_camera_vertical_pitch: 25.0
cameras:
    turret:
        input_width: 1280
        input_height: 720
        input_fps: 30
        output_width: 640
        output_height: 360
        output_fps: 30
        fov_degrees_x: 96.1
        fov_degrees_y: 55.4
    stream:
        input_width: 1280
        input_height: 1024
        input_fps: 20
        output_width: 320
        output_height: 240
        output_fps: 20
    front:
        serial: "DCD9E17F"
    rear:
        serial: "4B43D26F"
